# Generated by Django 3.2.7 on 2021-09-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='capa',
        ),
    ]
